---
# this comment is also a hack
version: "3"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:1.25.0
    # container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/syncthing/config:/config
      - /mnt/mobius/Music:/mnt/Music
      - /mnt/mobius/Documents:/mnt/Documents
      - /mnt/mobius/Pictures:/mnt/Pictures
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped